services:
  api-gateway:
    build:
      context: ../api-gateway-books
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka/
    networks:
      - books-network
    depends_on:
      - eureka-service